/* Generated By:JavaCC: Do not edit this line. LugosiParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FN = 5;
  /** RegularExpression Id. */
  int MAIN = 6;
  /** RegularExpression Id. */
  int LET = 7;
  /** RegularExpression Id. */
  int PRINTLN = 8;
  /** RegularExpression Id. */
  int READ_FLOAT = 9;
  /** RegularExpression Id. */
  int F32 = 10;
  /** RegularExpression Id. */
  int BOOL_TYPE = 11;
  /** RegularExpression Id. */
  int VOID_TYPE = 12;
  /** RegularExpression Id. */
  int ACHAVES = 13;
  /** RegularExpression Id. */
  int FCHAVES = 14;
  /** RegularExpression Id. */
  int SEMI = 15;
  /** RegularExpression Id. */
  int COLON = 16;
  /** RegularExpression Id. */
  int ASSIGN = 17;
  /** RegularExpression Id. */
  int ARROW = 18;
  /** RegularExpression Id. */
  int APARENTESES = 19;
  /** RegularExpression Id. */
  int FPARENTESES = 20;
  /** RegularExpression Id. */
  int IF = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int RETURN = 23;
  /** RegularExpression Id. */
  int TRUE = 24;
  /** RegularExpression Id. */
  int FALSE = 25;
  /** RegularExpression Id. */
  int SUM = 26;
  /** RegularExpression Id. */
  int SUB = 27;
  /** RegularExpression Id. */
  int MULT = 28;
  /** RegularExpression Id. */
  int DIV = 29;
  /** RegularExpression Id. */
  int AND = 30;
  /** RegularExpression Id. */
  int OR = 31;
  /** RegularExpression Id. */
  int MENOR = 32;
  /** RegularExpression Id. */
  int MAIOR = 33;
  /** RegularExpression Id. */
  int IGUAL = 34;
  /** RegularExpression Id. */
  int VIRGULA = 35;
  /** RegularExpression Id. */
  int NUM = 36;
  /** RegularExpression Id. */
  int ID = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"fn\"",
    "\"main\"",
    "\"let\"",
    "\"println!\"",
    "\"read_float\"",
    "\"f32\"",
    "\"bool\"",
    "\"void\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\":\"",
    "\"=\"",
    "\"->\"",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "\"while\"",
    "\"return\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\",\"",
    "<NUM>",
    "<ID>",
  };

}
