/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FN = 5;
  /** RegularExpression Id. */
  int LET = 6;
  /** RegularExpression Id. */
  int PRINTLN = 7;
  /** RegularExpression Id. */
  int F32 = 8;
  /** RegularExpression Id. */
  int I32 = 9;
  /** RegularExpression Id. */
  int BOOL_TYPE = 10;
  /** RegularExpression Id. */
  int ACHAVES = 11;
  /** RegularExpression Id. */
  int FCHAVES = 12;
  /** RegularExpression Id. */
  int SEMI = 13;
  /** RegularExpression Id. */
  int COLON = 14;
  /** RegularExpression Id. */
  int ASSIGN = 15;
  /** RegularExpression Id. */
  int APARENTESES = 16;
  /** RegularExpression Id. */
  int FPARENTESES = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int TRUE = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int SUM = 23;
  /** RegularExpression Id. */
  int SUB = 24;
  /** RegularExpression Id. */
  int MULT = 25;
  /** RegularExpression Id. */
  int DIV = 26;
  /** RegularExpression Id. */
  int AND = 27;
  /** RegularExpression Id. */
  int OR = 28;
  /** RegularExpression Id. */
  int MENOR = 29;
  /** RegularExpression Id. */
  int MAIOR = 30;
  /** RegularExpression Id. */
  int IGUAL = 31;
  /** RegularExpression Id. */
  int VIRGULA = 32;
  /** RegularExpression Id. */
  int NUM = 33;
  /** RegularExpression Id. */
  int ID = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"fn\"",
    "\"let\"",
    "\"println!\"",
    "\"f32\"",
    "\"i32\"",
    "\"bool\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\":\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "\"while\"",
    "\"return\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\",\"",
    "<NUM>",
    "<ID>",
  };

}
